// US area codes database: area code -> { state, city }
export const areaCodeMap: Record<string, { state: string; city: string }> = {
  "201": { state: "New Jersey", city: "Jersey City" },
  "202": { state: "Washington DC", city: "Washington" },
  "203": { state: "Connecticut", city: "Bridgeport" },
  "205": { state: "Alabama", city: "Birmingham" },
  "206": { state: "Washington", city: "Seattle" },
  "207": { state: "Maine", city: "Portland" },
  "208": { state: "Idaho", city: "Boise" },
  "209": { state: "California", city: "Stockton" },
  "210": { state: "Texas", city: "San Antonio" },
  "212": { state: "New York", city: "New York" },
  "213": { state: "California", city: "Los Angeles" },
  "214": { state: "Texas", city: "Dallas" },
  "215": { state: "Pennsylvania", city: "Philadelphia" },
  "216": { state: "Ohio", city: "Cleveland" },
  "217": { state: "Illinois", city: "Springfield" },
  "218": { state: "Minnesota", city: "Duluth" },
  "219": { state: "Indiana", city: "Gary" },
  "220": { state: "Ohio", city: "Newark" },
  "223": { state: "Pennsylvania", city: "Lancaster" },
  "224": { state: "Illinois", city: "Elgin" },
  "225": { state: "Louisiana", city: "Baton Rouge" },
  "228": { state: "Mississippi", city: "Gulfport" },
  "229": { state: "Georgia", city: "Albany" },
  "231": { state: "Michigan", city: "Muskegon" },
  "234": { state: "Ohio", city: "Akron" },
  "239": { state: "Florida", city: "Fort Myers" },
  "240": { state: "Maryland", city: "Germantown" },
  "248": { state: "Michigan", city: "Troy" },
  "251": { state: "Alabama", city: "Mobile" },
  "252": { state: "North Carolina", city: "Greenville" },
  "253": { state: "Washington", city: "Tacoma" },
  "254": { state: "Texas", city: "Killeen" },
  "256": { state: "Alabama", city: "Huntsville" },
  "260": { state: "Indiana", city: "Fort Wayne" },
  "262": { state: "Wisconsin", city: "Kenosha" },
  "267": { state: "Pennsylvania", city: "Philadelphia" },
  "269": { state: "Michigan", city: "Kalamazoo" },
  "270": { state: "Kentucky", city: "Bowling Green" },
  "272": { state: "Pennsylvania", city: "Scranton" },
  "276": { state: "Virginia", city: "Bristol" },
  "281": { state: "Texas", city: "Houston" },
  "301": { state: "Maryland", city: "Rockville" },
  "302": { state: "Delaware", city: "Wilmington" },
  "303": { state: "Colorado", city: "Denver" },
  "304": { state: "West Virginia", city: "Charleston" },
  "305": { state: "Florida", city: "Miami" },
  "307": { state: "Wyoming", city: "Cheyenne" },
  "308": { state: "Nebraska", city: "Grand Island" },
  "309": { state: "Illinois", city: "Peoria" },
  "310": { state: "California", city: "Los Angeles" },
  "312": { state: "Illinois", city: "Chicago" },
  "313": { state: "Michigan", city: "Detroit" },
  "314": { state: "Missouri", city: "St. Louis" },
  "315": { state: "New York", city: "Syracuse" },
  "316": { state: "Kansas", city: "Wichita" },
  "317": { state: "Indiana", city: "Indianapolis" },
  "318": { state: "Louisiana", city: "Shreveport" },
  "319": { state: "Iowa", city: "Cedar Rapids" },
  "320": { state: "Minnesota", city: "St. Cloud" },
  "321": { state: "Florida", city: "Orlando" },
  "323": { state: "California", city: "Los Angeles" },
  "325": { state: "Texas", city: "Abilene" },
  "330": { state: "Ohio", city: "Akron" },
  "331": { state: "Illinois", city: "Aurora" },
  "332": { state: "New York", city: "New York" },
  "334": { state: "Alabama", city: "Montgomery" },
  "336": { state: "North Carolina", city: "Greensboro" },
  "337": { state: "Louisiana", city: "Lafayette" },
  "339": { state: "Massachusetts", city: "Lynn" },
  "340": { state: "US Virgin Islands", city: "St. Thomas" },
  "346": { state: "Texas", city: "Houston" },
  "347": { state: "New York", city: "New York" },
  "351": { state: "Massachusetts", city: "Lowell" },
  "352": { state: "Florida", city: "Gainesville" },
  "360": { state: "Washington", city: "Vancouver" },
  "361": { state: "Texas", city: "Corpus Christi" },
  "364": { state: "Kentucky", city: "Owensboro" },
  "380": { state: "Ohio", city: "Columbus" },
  "385": { state: "Utah", city: "Salt Lake City" },
  "386": { state: "Florida", city: "Daytona Beach" },
  "401": { state: "Rhode Island", city: "Providence" },
  "402": { state: "Nebraska", city: "Omaha" },
  "404": { state: "Georgia", city: "Atlanta" },
  "405": { state: "Oklahoma", city: "Oklahoma City" },
  "406": { state: "Montana", city: "Billings" },
  "407": { state: "Florida", city: "Orlando" },
  "408": { state: "California", city: "San Jose" },
  "409": { state: "Texas", city: "Beaumont" },
  "410": { state: "Maryland", city: "Baltimore" },
  "412": { state: "Pennsylvania", city: "Pittsburgh" },
  "413": { state: "Massachusetts", city: "Springfield" },
  "414": { state: "Wisconsin", city: "Milwaukee" },
  "415": { state: "California", city: "San Francisco" },
  "417": { state: "Missouri", city: "Springfield" },
  "419": { state: "Ohio", city: "Toledo" },
  "423": { state: "Tennessee", city: "Chattanooga" },
  "424": { state: "California", city: "Los Angeles" },
  "425": { state: "Washington", city: "Bellevue" },
  "430": { state: "Texas", city: "Tyler" },
  "432": { state: "Texas", city: "Midland" },
  "434": { state: "Virginia", city: "Lynchburg" },
  "435": { state: "Utah", city: "St. George" },
  "440": { state: "Ohio", city: "Elyria" },
  "442": { state: "California", city: "Oceanside" },
  "443": { state: "Maryland", city: "Baltimore" },
  "458": { state: "Oregon", city: "Eugene" },
  "463": { state: "Indiana", city: "Indianapolis" },
  "469": { state: "Texas", city: "Dallas" },
  "470": { state: "Georgia", city: "Atlanta" },
  "475": { state: "Connecticut", city: "Bridgeport" },
  "478": { state: "Georgia", city: "Macon" },
  "479": { state: "Arkansas", city: "Fort Smith" },
  "480": { state: "Arizona", city: "Mesa" },
  "484": { state: "Pennsylvania", city: "Allentown" },
  "501": { state: "Arkansas", city: "Little Rock" },
  "502": { state: "Kentucky", city: "Louisville" },
  "503": { state: "Oregon", city: "Portland" },
  "504": { state: "Louisiana", city: "New Orleans" },
  "505": { state: "New Mexico", city: "Albuquerque" },
  "507": { state: "Minnesota", city: "Rochester" },
  "508": { state: "Massachusetts", city: "Worcester" },
  "509": { state: "Washington", city: "Spokane" },
  "510": { state: "California", city: "Oakland" },
  "512": { state: "Texas", city: "Austin" },
  "513": { state: "Ohio", city: "Cincinnati" },
  "515": { state: "Iowa", city: "Des Moines" },
  "516": { state: "New York", city: "Hempstead" },
  "517": { state: "Michigan", city: "Lansing" },
  "518": { state: "New York", city: "Albany" },
  "520": { state: "Arizona", city: "Tucson" },
  "530": { state: "California", city: "Redding" },
  "531": { state: "Nebraska", city: "Omaha" },
  "534": { state: "Wisconsin", city: "Eau Claire" },
  "539": { state: "Oklahoma", city: "Tulsa" },
  "540": { state: "Virginia", city: "Roanoke" },
  "541": { state: "Oregon", city: "Eugene" },
  "551": { state: "New Jersey", city: "Jersey City" },
  "559": { state: "California", city: "Fresno" },
  "561": { state: "Florida", city: "West Palm Beach" },
  "562": { state: "California", city: "Long Beach" },
  "563": { state: "Iowa", city: "Davenport" },
  "567": { state: "Ohio", city: "Toledo" },
  "570": { state: "Pennsylvania", city: "Scranton" },
  "571": { state: "Virginia", city: "Arlington" },
  "573": { state: "Missouri", city: "Columbia" },
  "574": { state: "Indiana", city: "South Bend" },
  "575": { state: "New Mexico", city: "Las Cruces" },
  "580": { state: "Oklahoma", city: "Lawton" },
  "585": { state: "New York", city: "Rochester" },
  "586": { state: "Michigan", city: "Warren" },
  "601": { state: "Mississippi", city: "Jackson" },
  "602": { state: "Arizona", city: "Phoenix" },
  "603": { state: "New Hampshire", city: "Manchester" },
  "605": { state: "South Dakota", city: "Sioux Falls" },
  "606": { state: "Kentucky", city: "Ashland" },
  "607": { state: "New York", city: "Binghamton" },
  "608": { state: "Wisconsin", city: "Madison" },
  "609": { state: "New Jersey", city: "Trenton" },
  "610": { state: "Pennsylvania", city: "Allentown" },
  "612": { state: "Minnesota", city: "Minneapolis" },
  "614": { state: "Ohio", city: "Columbus" },
  "615": { state: "Tennessee", city: "Nashville" },
  "616": { state: "Michigan", city: "Grand Rapids" },
  "617": { state: "Massachusetts", city: "Boston" },
  "618": { state: "Illinois", city: "Belleville" },
  "619": { state: "California", city: "San Diego" },
  "620": { state: "Kansas", city: "Dodge City" },
  "623": { state: "Arizona", city: "Glendale" },
  "626": { state: "California", city: "Pasadena" },
  "628": { state: "California", city: "San Francisco" },
  "629": { state: "Tennessee", city: "Nashville" },
  "630": { state: "Illinois", city: "Naperville" },
  "631": { state: "New York", city: "Islip" },
  "636": { state: "Missouri", city: "O'Fallon" },
  "641": { state: "Iowa", city: "Mason City" },
  "646": { state: "New York", city: "New York" },
  "650": { state: "California", city: "San Mateo" },
  "651": { state: "Minnesota", city: "St. Paul" },
  "657": { state: "California", city: "Anaheim" },
  "660": { state: "Missouri", city: "Sedalia" },
  "661": { state: "California", city: "Bakersfield" },
  "662": { state: "Mississippi", city: "Tupelo" },
  "667": { state: "Maryland", city: "Baltimore" },
  "669": { state: "California", city: "San Jose" },
  "678": { state: "Georgia", city: "Atlanta" },
  "680": { state: "New York", city: "Syracuse" },
  "681": { state: "West Virginia", city: "Charleston" },
  "682": { state: "Texas", city: "Fort Worth" },
  "689": { state: "Florida", city: "Orlando" },
  "701": { state: "North Dakota", city: "Fargo" },
  "702": { state: "Nevada", city: "Las Vegas" },
  "703": { state: "Virginia", city: "Arlington" },
  "704": { state: "North Carolina", city: "Charlotte" },
  "706": { state: "Georgia", city: "Augusta" },
  "707": { state: "California", city: "Santa Rosa" },
  "708": { state: "Illinois", city: "Cicero" },
  "712": { state: "Iowa", city: "Sioux City" },
  "713": { state: "Texas", city: "Houston" },
  "714": { state: "California", city: "Anaheim" },
  "715": { state: "Wisconsin", city: "Eau Claire" },
  "716": { state: "New York", city: "Buffalo" },
  "717": { state: "Pennsylvania", city: "Lancaster" },
  "718": { state: "New York", city: "New York" },
  "719": { state: "Colorado", city: "Colorado Springs" },
  "720": { state: "Colorado", city: "Denver" },
  "724": { state: "Pennsylvania", city: "New Castle" },
  "725": { state: "Nevada", city: "Las Vegas" },
  "726": { state: "Texas", city: "San Antonio" },
  "727": { state: "Florida", city: "St. Petersburg" },
  "731": { state: "Tennessee", city: "Jackson" },
  "732": { state: "New Jersey", city: "New Brunswick" },
  "734": { state: "Michigan", city: "Ann Arbor" },
  "737": { state: "Texas", city: "Austin" },
  "740": { state: "Ohio", city: "Lancaster" },
  "743": { state: "North Carolina", city: "Greensboro" },
  "747": { state: "California", city: "Los Angeles" },
  "754": { state: "Florida", city: "Fort Lauderdale" },
  "757": { state: "Virginia", city: "Virginia Beach" },
  "760": { state: "California", city: "Oceanside" },
  "762": { state: "Georgia", city: "Augusta" },
  "763": { state: "Minnesota", city: "Brooklyn Park" },
  "765": { state: "Indiana", city: "Muncie" },
  "769": { state: "Mississippi", city: "Jackson" },
  "770": { state: "Georgia", city: "Roswell" },
  "772": { state: "Florida", city: "Port St. Lucie" },
  "773": { state: "Illinois", city: "Chicago" },
  "774": { state: "Massachusetts", city: "Worcester" },
  "775": { state: "Nevada", city: "Reno" },
  "779": { state: "Illinois", city: "Rockford" },
  "781": { state: "Massachusetts", city: "Wellesley" },
  "785": { state: "Kansas", city: "Topeka" },
  "786": { state: "Florida", city: "Miami" },
  "801": { state: "Utah", city: "Salt Lake City" },
  "802": { state: "Vermont", city: "Burlington" },
  "803": { state: "South Carolina", city: "Columbia" },
  "804": { state: "Virginia", city: "Richmond" },
  "805": { state: "California", city: "Santa Barbara" },
  "806": { state: "Texas", city: "Lubbock" },
  "808": { state: "Hawaii", city: "Honolulu" },
  "810": { state: "Michigan", city: "Flint" },
  "812": { state: "Indiana", city: "Evansville" },
  "813": { state: "Florida", city: "Tampa" },
  "814": { state: "Pennsylvania", city: "Erie" },
  "815": { state: "Illinois", city: "Rockford" },
  "816": { state: "Missouri", city: "Kansas City" },
  "817": { state: "Texas", city: "Fort Worth" },
  "818": { state: "California", city: "Burbank" },
  "820": { state: "California", city: "Santa Barbara" },
  "828": { state: "North Carolina", city: "Asheville" },
  "830": { state: "Texas", city: "New Braunfels" },
  "831": { state: "California", city: "Salinas" },
  "832": { state: "Texas", city: "Houston" },
  "835": { state: "Pennsylvania", city: "Allentown" },
  "838": { state: "New York", city: "Albany" },
  "843": { state: "South Carolina", city: "Charleston" },
  "845": { state: "New York", city: "New City" },
  "847": { state: "Illinois", city: "Elgin" },
  "848": { state: "New Jersey", city: "New Brunswick" },
  "850": { state: "Florida", city: "Tallahassee" },
  "854": { state: "South Carolina", city: "Charleston" },
  "856": { state: "New Jersey", city: "Camden" },
  "857": { state: "Massachusetts", city: "Boston" },
  "858": { state: "California", city: "San Diego" },
  "859": { state: "Kentucky", city: "Lexington" },
  "860": { state: "Connecticut", city: "Hartford" },
  "862": { state: "New Jersey", city: "Newark" },
  "863": { state: "Florida", city: "Lakeland" },
  "864": { state: "South Carolina", city: "Greenville" },
  "865": { state: "Tennessee", city: "Knoxville" },
  "870": { state: "Arkansas", city: "Jonesboro" },
  "872": { state: "Illinois", city: "Chicago" },
  "878": { state: "Pennsylvania", city: "Pittsburgh" },
  "901": { state: "Tennessee", city: "Memphis" },
  "903": { state: "Texas", city: "Tyler" },
  "904": { state: "Florida", city: "Jacksonville" },
  "906": { state: "Michigan", city: "Marquette" },
  "907": { state: "Alaska", city: "Anchorage" },
  "908": { state: "New Jersey", city: "Elizabeth" },
  "909": { state: "California", city: "San Bernardino" },
  "910": { state: "North Carolina", city: "Fayetteville" },
  "912": { state: "Georgia", city: "Savannah" },
  "913": { state: "Kansas", city: "Kansas City" },
  "914": { state: "New York", city: "Yonkers" },
  "915": { state: "Texas", city: "El Paso" },
  "916": { state: "California", city: "Sacramento" },
  "917": { state: "New York", city: "New York" },
  "918": { state: "Oklahoma", city: "Tulsa" },
  "919": { state: "North Carolina", city: "Raleigh" },
  "920": { state: "Wisconsin", city: "Green Bay" },
  "925": { state: "California", city: "Concord" },
  "928": { state: "Arizona", city: "Yuma" },
  "929": { state: "New York", city: "New York" },
  "930": { state: "Indiana", city: "Evansville" },
  "931": { state: "Tennessee", city: "Clarksville" },
  "934": { state: "New York", city: "Islip" },
  "936": { state: "Texas", city: "Conroe" },
  "937": { state: "Ohio", city: "Dayton" },
  "938": { state: "Alabama", city: "Huntsville" },
  "940": { state: "Texas", city: "Denton" },
  "941": { state: "Florida", city: "Sarasota" },
  "943": { state: "Georgia", city: "Savannah" },
  "945": { state: "Texas", city: "Dallas" },
  "947": { state: "Michigan", city: "Troy" },
  "949": { state: "California", city: "Irvine" },
  "951": { state: "California", city: "Riverside" },
  "952": { state: "Minnesota", city: "Bloomington" },
  "954": { state: "Florida", city: "Fort Lauderdale" },
  "956": { state: "Texas", city: "Laredo" },
  "959": { state: "Connecticut", city: "Hartford" },
  "970": { state: "Colorado", city: "Fort Collins" },
  "971": { state: "Oregon", city: "Portland" },
  "972": { state: "Texas", city: "Dallas" },
  "973": { state: "New Jersey", city: "Newark" },
  "978": { state: "Massachusetts", city: "Lowell" },
  "979": { state: "Texas", city: "College Station" },
  "980": { state: "North Carolina", city: "Charlotte" },
  "984": { state: "North Carolina", city: "Raleigh" },
  "985": { state: "Louisiana", city: "Houma" },
  "989": { state: "Michigan", city: "Saginaw" },
};

export function detectStateFromNumber(number: string): { state: string; city: string } | null {
  const cleaned = number.replace(/\D/g, '');
  let areaCode = '';
  if (cleaned.length === 11 && cleaned.startsWith('1')) {
    areaCode = cleaned.substring(1, 4);
  } else if (cleaned.length === 10) {
    areaCode = cleaned.substring(0, 3);
  } else if (cleaned.startsWith('+1') && cleaned.length >= 5) {
    areaCode = cleaned.substring(2, 5);
  }
  return areaCodeMap[areaCode] || null;
}

export function groupNumbersByState(numbers: string[]): Record<string, { numbers: string[]; city: string }> {
  const groups: Record<string, { numbers: string[]; city: string; cities: Record<string, string[]> }> = {};
  for (const num of numbers) {
    const info = detectStateFromNumber(num);
    const state = info?.state || 'Unknown';
    const city = info?.city || '';
    if (!groups[state]) groups[state] = { numbers: [], city, cities: {} };
    groups[state].numbers.push(num);
    if (city) {
      if (!groups[state].cities[city]) groups[state].cities[city] = [];
      groups[state].cities[city].push(num);
    }
  }
  return groups;
}
